### ISSUE TITLE
setup help

### ISSUE THREAD

**Issue by pepone** [MirageNet/nunit-reporter#22]
Hi, 

I'm trying to setup nunit-reporter with my .NET 6 project

I have
```
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger:"nunit;LogFilePath=TestResults/TestResults.xml"
    - name: NUnit Reporter
      uses: MirageNet/nunit-reporter@v1.0.5
      if: always()
      with:
        path: tests/*/TestResults/TestResults.xml
        access-token: ${{ secrets.GITHUB_TOKEN }}
```

But the reporter step fails with

```
Run MirageNet/nunit-reporter@v1.0.5
  with:
    path: tests/*/TestResults/TestResults.xml
    access-token: ***
    numFailures: 30
  env:
    DOTNET_ROOT: /home/runner/.dotnet
    SSH_AUTH_SOCK: /tmp/ssh-eAwEOAlnnS92/agent.1827
    SSH_AGENT_PID: 1828
Error: Resource not accessible by integration
```

Can you tell me what is wrong with my setup?

Cheers,
Jose

**Comment by paulpach** [comment]
do you have a repro build?

**Comment by paulpach** [comment]
Can you try with version 1.1.0?

**Comment by pepone** [comment]
Tried with 1.10 version
```
Run MirageNet/nunit-reporter@v1.1.0
  with:
    path: tests/IceRpc.Tests.ClientServer/TestResults/TestResults.xml
    access-token: ***
    numFailures: [3](https://github.com/zeroc-ice/icerpc-csharp/pull/778/checks#step:12:3)0
    reportTitle: Test Report
  env:
    DOTNET_ROOT: /home/runner/.dotnet
    SSH_AUTH_SOCK: /tmp/ssh-m9dQwVqXv9Fo/agent.19[4](https://github.com/zeroc-ice/icerpc-csharp/pull/778/checks#step:12:4)[6](https://github.com/zeroc-ice/icerpc-csharp/pull/778/checks#step:12:6)
    SSH_AGENT_PID: 194[7](https://github.com/zeroc-ice/icerpc-csharp/pull/778/checks#step:12:7)
Error: Resource not accessible by integration
```

This is a private repository, not sure if this matters

**Comment by pepone** [comment]
tried with 1.10
```
Run MirageNet/nunit-reporter@v1.1.0
  with:
    path: tests/Tests.ClientServer/TestResults/TestResults.xml
    access-token: ***
    numFailures: 30
    reportTitle: Test Report
  env:
    DOTNET_ROOT: /home/runner/.dotnet
    SSH_AUTH_SOCK: /tmp/ssh-m9dQwVqXv9Fo/agent.1946
    SSH_AGENT_PID: 1947
Error: Resource not accessible by integration
```
I'm using it from a private repository, not sure if that matters.

**Comment by paulpach** [comment]
is this running in a PR for a fork by any chance?

I found [this](https://github.com/actions/first-interaction/issues/10)
And some good read [here](https://github.community/t/github-actions-are-severely-limited-on-prs/18179#M9249).

Assuming you are sending a PR from a fork,  would it be possible for you to get an access token to the origin repo?  if so,  you can create a token there and use it instead of secrets.GITHUB_TOKEN

**Comment by pepone** [comment]
This is running in a PR from a fork. I setup a GitHub token and get a different error

```
Error: You must authenticate via a GitHub App.
```

My repository is a mix of Rust and C# on the rust side I run `actions-rs/clippy@master` and this correctly annotates the rust build without additional permissions, it is not clear why nunit-reporter needs additional permissions.

**Comment by paulpach** [comment]
From the readme, it seems the entire motivation for actions-rs/clippy was to replace clippy-check  so that it would not require GITHUB_TOKEN and it would work on prs from forks.

I'll check how they do that.

**Comment by paulpach** [comment]
Ok,  I implemented the same hack they did,  can you try this branch before I merge it?  like this:

```YAML
- uses: MirageNet/nunit-reporter@accesscode
      if: always()
      with:
        path: Tests/*.xml
```
