### ISSUE TITLE
Repository not found : mirrorng/nunit-reporter

### ISSUE THREAD

**Issue by teng-wu** [MirageNet/nunit-reporter#24]
Hi,  I am using the following yml code. I got an error said "Repository not found : mirrorng/nunit-reporter".
Could you please tell me which repo path to use?

```
      - uses: MirrorNG/nunit-reporter@v1.0.9
        if: always()
        with:
          path: _build/*.xml
          access-token: ${{ secrets.TOKEN_GITHUB_REGISTRY }}
```

Getting action download info
Error: Unable to resolve actions. Repository not found : mirrorng/nunit-reporter.
